// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Leggy",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Leggy",
            targets: ["AppModule"],
            bundleIdentifier: "-.Leggy",
            teamIdentifier: "H4M7KJL5DT",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "To scan texts and transport them in the application")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Font")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)